# Generated by Django 4.1.2 on 2023-06-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Solicitud', models.DateField(auto_now_add=True)),
                ('Nombre_Contacto', models.CharField(max_length=255)),
                ('Correo_Contacto', models.EmailField(max_length=255)),
                ('Numero_Contacto', models.CharField(max_length=12)),
                ('Descripcion_Contacto', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo_Mensaje', models.EmailField(max_length=255)),
                ('Descripcion_Mensaje', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Vehiculo', models.CharField(max_length=255)),
                ('Anno_Vehiculo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesMecanicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto_Mecanico', models.ImageField(upload_to='fotosMecanicos')),
                ('id_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_mecanicos', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mecanico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Atencion', models.DateField(default=django.utils.timezone.now)),
                ('Fotos_Atencion', models.ImageField(null=True, upload_to='imagenesMecanicos')),
                ('Diagnostico_Atencion', models.TextField(max_length=1000)),
                ('MaterialesUsados', models.CharField(max_length=1000)),
                ('EstadoTrabajo', models.TextField(blank=True, max_length=1000)),
                ('id_Estado', models.IntegerField(max_length=1)),
                ('id_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_mecanico_atencion', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nombre_mecanico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
