# Generated by Django 4.1.2 on 2023-06-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mecanico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='id_Estado',
            field=models.IntegerField(),
        ),
    ]
