# Generated by Django 4.1.2 on 2023-06-27 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mecanico', '0002_alter_atencion_id_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='id_user_id',
            new_name='id_user',
        ),
        migrations.AlterField(
            model_name='atencion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombre_mecanico', to=settings.AUTH_USER_MODEL),
        ),
    ]
